parametros_regresion:
  test_size: 0.2
  random_state: 42
  feature: ["total_episodios", "popularidad", "favoritos"]
  target: "puntuacion"
  n_iter: 5
  cv: 5

parametros_clasificacion:
  test_size: 0.2
  random_state: 42

# Nombres para los títulos de los gráficos de regresión
LinearRegression_name: "Linear Regression"
Ridge_name: "Ridge Regression"
Lasso_name: "Lasso Regression"
RandomForest_name: "Random Forest"
GradientBoosting_name: "Gradient Boosting"