parametros_regresion:
  test_size: 0.2
  random_state: 42
  feature: ["total_episodios", "popularidad", "favoritos"]
  target: "puntuacion"
  n_iter: 5
  cv: 5

parametros_clasificacion:
  test_size: 0.2
  random_state: 42

# Nombres para los títulos de los gráficos de regresión
model_names:
  LinearRegression: "LinearRegression"
  Ridge: "Ridge"
  Lasso: "Lasso"
  RandomForest: "RandomForest"
  GradientBoosting: "GradientBoosting"

# Nombres para los títulos de los gráficos de clasificación
parametros_modelos_clasificacion:
  LogisticRegression: "LogisticRegression"
  SGDClassifier: "SGDClassifier"
  RandomForest: "RandomForest"
  DecisionTree: "DecisionTree"
  KNeighborsClassifier: "KNeighborsClassifier"

parametros_clustering:
  K_FINAL: 2
  random_state: 42
  features_cols: ["puntuacion", "miembros", "favoritos", "total_episodios"]
  scaler: "StandardScaler"
  n_neighbors: 15
  min_dist: 0.1
  contamination: 0.05
