parametros_regresion:
  test_size: 0.2
  random_state: 42
  feature: ["total_episodios", "popularidad", "favoritos"]
  target: "puntuacion"
  n_iter: 5
  cv: 5

parametros_clasificacion:
  test_size: 0.2
  random_state: 42

# Nombres para los títulos de los gráficos de regresión
model_names:
  LinearRegression: "LinearRegression"
  Ridge: "Ridge"
  Lasso: "Lasso"
  RandomForest: "RandomForest"
  GradientBoosting: "GradientBoosting"

# Nombres para los títulos de los gráficos de clasificación
parametros_modelos_clasificacion:
  LogisticRegression: "LogisticRegression"
  SGDClassifier: "SGDClassifier"
  RandomForest: "RandomForest"
  DecisionTree: "DecisionTree"
  KNeighborsClassifier: "KNeighborsClassifier"
